[package]
name = "engine"
version = "1.0.1"
edition = "2021"
authors = ["Ludovic Debever ludovicdebever0@gmail.com", 'Eliott Reigner', 'Mahdi Aribi']
description = "Pluto Chess Engine"
repository = "https://github.com/Lxdovic/pluto"

[lib]
crate-type = ["rlib"]
name = "engine"
path = "src/lib.rs"

[[bin]]
name = "engine"
path = "src/main.rs"

[features]
default = ["classical"]
tuning = []
classical = []
log = []
datagen = []

[dependencies]
queues = "1.1.0"
shakmaty = "0.29.1"
serde_derive = "1.0.215"
toml = "0.8.19"
serde = "1.0.215"
wasm-bindgen = "0.2.100"
chrono = "0.4.40"
web-sys = { version = "0.3.77", features = [
    'Worker',
] }
log = "0.4"
simplelog = "0.12"
